const EDIT_FIRST = "EDIT_GROUP_FIRST";
const EDIT_MODAL = "EDIT_MODAL";
const DELETE = "DELETE";
const ADD = "ADD";

const HANDLE_CANCEL = "HANDLE_CANCEL";
const SHOW_MODAL = "SHOW_MODAL";

export { EDIT_FIRST, EDIT_MODAL, DELETE, ADD, HANDLE_CANCEL, SHOW_MODAL };
